### ISSUE TITLE
Issue with device being returned in User Agent

### ISSUE THREAD

**Issue by heynemann** [selwin/python-user-agents#39]
I'm having a traceback like this:

    Traceback (most recent call last):
      File "/Users/heynemann/Dropbox/dev/thumby-dashboard/tests/elasticsearch/test_request_model.py", line 97, in test_can_process_request_log_from_cloudfront
        request_id = Request.perform(log_line)
      File "/Users/heynemann/Dropbox/dev/thumby-dashboard/thumby_dashboard/models/elasticsearch/request.py", line 76, in perform
        items = parse(cloudfront_log_lines)
      File "/Users/heynemann/.virtualenvs/thumby/lib/python2.7/site-packages/cloudfront_log_parser/__init__.py", line 42, in parse
        result.append(parse_line(line))
      File "/Users/heynemann/.virtualenvs/thumby/lib/python2.7/site-packages/cloudfront_log_parser/__init__.py", line 81, in parse_line
        parse_user_agent(response, log_line[10])
      File "/Users/heynemann/.virtualenvs/thumby/lib/python2.7/site-packages/cloudfront_log_parser/__init__.py", line 109, in parse_user_agent
        user_agent = user_agent_parse(response.user_agent)
      File "/Users/heynemann/.virtualenvs/thumby/lib/python2.7/site-packages/user_agents/parsers.py", line 226, in parse
        return UserAgent(user_agent_string)
      File "/Users/heynemann/.virtualenvs/thumby/lib/python2.7/site-packages/user_agents/parsers.py", line 129, in __init__
        self.device = parse_device(**ua_dict['device'])
    TypeError: parse_device() got an unexpected keyword argument 'brand'

The user agent  being parsed is:

    curl/7.37.1

Any ideas on what might be causing it?

**Comment by heynemann** [comment]
I'm sorry. Updating to release 1.0.1 fixed it.

Closing this issue.
